
server:
    port: 8401
spring:
    application:
        name: hystrix-service
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8001/eureka/
service-url:
    biz-service: http://biz-service

hystrix:
    metrics:
        enabled: true