server:
    port: 8301
spring:
    application:
        name: load-balancer-service
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8001/eureka/
service-url:
    biz-service: http://biz-service/